[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.2",
    "opencv-python-headless>=4.11.0.86",
    "ultralytics>=8.3.23",
]
